version: "3.9"
services:
  api:
    container_name: node
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}

  redis:
    image: redis
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_PASS} --appendonly yes
    hostname: redis
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/data
    restart: always

volumes:
  redis: {}